#! /bin/sh

# Credits to
# - tmuxifier: https://github.com/jimeh/tmuxifier
# - shmux: https://github.com/typecraft-dev/shmux
# - ThePrimeagen's sessionizer script: https://github.com/ThePrimeagen/.dotfiles/

usage() {
    cat <<EOF
Usage:
    help                   --  Because sometimes you just don't know... ¯\_(ツ)_/¯

    # Listing and Inspection
    ls                     --  Only the important shi- ... I mean running sessions and layouts.
       -a                  --  Gimme all you have! Not blazingly fast.
    preview -s [session]   --  To be used before switching sides.
            -l [layout]    --  Whats in there? *taps layout*
            -f [fragment]  --  What are THOOSE?
            -d [dir]       --  Like window shopping for code.

    # Editing
    edit -l [layout]       --  Where and mistakes happen.
         -f [fragment]     --  Small but mighty!  Handle with care.
         dirs              --  Tell me where the files are, Obi-Wan.

    # Session Management
    pick                   --  Pick your poison.
    [input]                --  New session. Who dis?
                           --    From layout:  Instant architecture!
                           --    From fragment:  Lego time!
                           --    Named session: Good ol' fashion session!
    .                      --  Session! Where? Here! When? Now!
    (no arguments)         --  Attach to the last session. Ahh shit... here we go again.
EOF
}

if [[ $# -gt 0 ]]; then
    case "$1" in
    esac
else
    if [ -z "$TMUX" ]; then
        tmux attach 2>/dev/null || { echo "Error: Tmux is not running" ; exit 1; }
    else
        echo "Error: already attached"
        exit 1
    fi
fi
