#!/bin/sh

# Credits to
# - tmuxifier: https://github.com/jimeh/tmuxifier
# - shmux: https://github.com/typecraft-dev/shmux
# - ThePrimeagen's sessionizer script: https://github.com/ThePrimeagen/.dotfiles/

# FIX: error handling
# especially for sub commands

. $TX_ROOT/helpers.sh

usage() {
    cat <<EOF
Usage:
    help                   --  Because sometimes you just don't know... ¯\_(ツ)_/¯

    # Listing and Inspection
    ls                     --  Only the important shi- ... I mean running sessions and layouts.
       -a                  --  Gimme all you have! Not blazingly fast.
    preview -s [session]   --  To be used before switching sides.
            -l [layout]    --  Whats in there? *taps layout*
            -f [fragment]  --  What are THOOSE?
            -d [dir]       --  Like window shopping for code.

    # Editing
    edit -l [layout]       --  Where and mistakes happen.
         -f [fragment]     --  Small but mighty! Handle with care.
         dirs              --  Tell me where the files are, Obi-Wan.

    # Session Management
    pick                   --  Limited stock. Session or layout?
    switch                 --  I changed my mind. Last session was better.
    sesh                   --  Which directory we're dropping in bois?
    [input]                --  New session. Who dis?
                           --    From layout: Instant architecture!
                           --    From fragment: Lego time!
                           --    Named session: Good ol' fashion session!
    .                      --  Session! Where? Here!
    (no arguments)         --  Attach to the last session. Ahh shit... here we go again.
EOF

    if [ -n "$1" ]; then
        exit 1
    fi
}

list() {
    declare -A session_set
    remove_duplicates() {
        local input="$1"
        local output=""
        while IFS= read -r item; do
            if [ ! ${session_set["$item"]} ]; then
                output+="$item"$'\n'
            fi
        done <<< "$input"
        echo -n "$output"
    }

    local sessions=$(get_tmux_sessions "#{session_name}")

    if [ -n "$sessions" ]; then
        while IFS= read -r session; do
          session_set["$session"]=1
        done <<< "$sessions"
    fi

    local layouts=$(remove_duplicates "$(get_layouts)")
    local fragments=""
    local dir_paths=""

    if [ "$1" = "-a" ]; then
        fragments=$(get_fragments)

        dir_paths=$(get_dir_paths)
        if [ "$?" -ne 0 ]; then
            echo "$dir_paths"
            exit 1
        fi
    fi

    local max_len=$(
        {
            echo "$sessions";
            echo "$layouts";
            echo "$fragments";
            echo "$dir_paths";
        } | awk '{print length}' | sort -nr | head -1
    )

    get_tmux_sessions "#{session_attached}:#{session_last_attached}:#{session_name}:#{session_windows}" |\
    sort -t: -k1,1n -k2,2nr |\
    while IFS=':' read -r is_attached last_attached session_name num_windows; do
        local attached_str=""
        if [ "$is_attached" = "1" ]; then
            attached_str=" (attached)"
        fi
        printf "%-*s (session) (%s windows)%s\n" "$max_len" "$session_name" "$num_windows" "$attached_str"
    done

    echo "$layouts" | awk -v max_len="$max_len" '{printf "%-*s (layout)\n", max_len, $0}'

    if [ -n "$fragments" ]; then
        echo "$fragments" | awk -v max_len="$max_len" '{printf "%-*s (fragment)\n", max_len, $0}'
    fi

    if [ -n "$dir_paths" ]; then
        echo "$dir_paths" | awk -v max_len="$max_len" '{printf "%-*s (directory)\n", max_len, $0}'
    fi
}

preview() {
    local filter="$1"
    local name="$2"

    case "$filter" in
        -s)
            if get_tmux_sessions "#{session_name}" | grep -qx "$name"; then
                tmux capture-pane -ep -t "$name"
            else
                echo "Error: session $name not found"
                exit 1
            fi
            ;;
        -l)
            if is_layout "$name"; then
                bat --paging=never --style=plain --language=sh --color=always "$DATA_DIR/$name$LAYOUT_EXT"
            else
                echo "Error: layout $name not found"
                exit 1
            fi
            ;;
        -f)
            if is_fragment "$name"; then
                bat --paging=never --style=plain --language=sh --color=always "$DATA_DIR/$name$FRAGMENT_EXT"
            else
                echo "Error: fragment $name not found"
                exit 1
            fi
            ;;
        -d)
            local path=$(get_full_dir_path "$name")
            if [ -n "$path" ]; then
                eza --group-directories-first -lah "$path" --color=always
            else
                echo "Error: directory $name not found"
                exit 1
            fi
            ;;
        *)
            echo "Error: unknown filter $filter"
            exit 1
            ;;
    esac
}

pick() {
    local inner_awk='{
        match($0, /\(([^)]+)\)/, arr);
        type = substr(arr[1], 1, 1);
        gsub(/\(.*\)/, "", $0);
        name = $0
        gsub(/[[:space:]]+$/, "", name)
        printf "tx preview -%s \"%s\"", type, name
    }'
    local awk_cmd="awk '$inner_awk'"
    local while_cmd='while read -r line; do echo \"$line\"; done'
    local preview_cmd="echo {} | $awk_cmd | bash"

    local selected=$(picker "$(list)" "$preview_cmd")

    if [ -z "$selected" ]; then
        exit 1
    fi

    IFS=":" read name type <<< $(
        echo "$selected" |\
        awk '{
            match($0, /\(([^)]+)\)/, arr)
            type = substr(arr[1], 1, 1)
            gsub(/\(.*\)/, "", $0)
            name = $0
            gsub(/[[:space:]]+$/, "", name)
            print name ":" type
        }'
    )

    case "$type" in
        s)
            tmux_attach_or_switch "$name"
            ;;
        l)
            . "$DATA_DIR/$name$LAYOUT_EXT"
            ;;
        *)
            ;;
    esac
}

switch() {
    local last=$(list | head -1)
    if [ -z "$last" ]; then
        exit 1
    fi

    IFS=":" read name type <<< $(
        echo "$last" |\
        awk '{
            match($0, /\(([^)]+)\)/, arr)
            type = substr(arr[1], 1, 1)
            gsub(/\(.*\)/, "", $0)
            name = $0
            gsub(/[[:space:]]+$/, "", name)
            print name ":" type
        }'
    )

    case "$type" in
        s)
            tmux_attach_or_switch "$name"
            ;;
        l)
            . "$DATA_DIR/$name$LAYOUT_EXT"
            ;;
        *)
            ;;
    esac
}

edit() {
    local filter="$1"
    local name="$2"
    local file

    case "$filter" in
        -l)
            file="$DATA_DIR/$name$LAYOUT_EXT"
            if [ ! -f "$file" ]; then
                default_layout "$name" "$file"
                chmod 744 "$file"
            fi
            ;;
        -f)
            file="$DATA_DIR/$name$FRAGMENT_EXT"
            if [ ! -f "$file" ]; then
                default_fragment "$name" "$file"
                chmod 744 "$file"
            fi
            ;;
        dirs)
            file="$DIR_PATHS_FILE"
            ;;
        *)
            echo "Error: unknown filter $filter"
            exit 1
            ;;
    esac

    $EDITOR "$file"
}

sesh() {
    local preview_cmd="basename {} | xargs -I{} tx preview -d {}"
    local selected=$(picker "$(get_dir_paths)" "$preview_cmd")
    local dir=$(get_full_dir_path "$selected")
    local name=$(basename "$dir")

    if [ -z "$selected" ]; then
        exit 1
    fi

    while is_session "$name"; do
        name="$RANDOM"
    done

    tmux new-session -d -s "$name" -c "$dir"
    tmux_attach_or_switch "$name"
}

new_session() {
    local name="$1"

    if get_tmux_sessions "#{session_name}" | grep -qx "$name"; then
        tmux_attach_or_switch "$name"
        return 0
    fi

    if is_layout "$name"; then
        . "$DATA_DIR/$name$LAYOUT_EXT"
        return 0
    fi

    if is_fragment "$name"; then
        echo "fragment $name"
        return 0
    fi
}

if [ $# -gt 0 ]; then
    case "$1" in
        help)
            usage
            ;;
        ls)
            list "$2"
            ;;
        preview)
            preview "$2" "$3"
            ;;
        pick)
            pick
            ;;
        switch)
            switch
            ;;
        edit)
            edit "$2" "$3"
            ;;
        sesh)
            sesh
            ;;
        .)
            tmux
            ;;
        *)
            new_session "$1"
    esac
else
    if [ -z "$TMUX" ]; then
        tmux attach 2>/dev/null || { echo "Error: tmux is not running" ; exit 1; }
    else
        echo "Error: already attached"
        exit 1
    fi
fi
